# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('votations', '0010_auto_20180304_1751'),
        ('books', '0008_auto_20180302_1433'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(auto_now=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('timezone', models.CharField(blank=True, max_length=120, null=True)),
                ('books_rated', models.ManyToManyField(related_name='profiles_added_rating', to='votations.Rating')),
                ('books_reviewed', models.ManyToManyField(related_name='profiles_added_review', to='books.Book')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
