# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 16:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='ratings',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
