# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0005_votation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='votation',
            name='month',
            field=models.CharField(choices=[('ja', 'January'), ('fe', 'February'), ('ma', 'March'), ('ap', 'April'), ('may', 'May'), ('ju', 'June'), ('jul', 'July'), ('au', 'August'), ('se', 'September'), ('oc', 'October'), ('no', 'November'), ('de', 'December')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='votation',
            name='position',
            field=models.CharField(choices=[('f', 'First'), ('s', 'Second'), ('t', 'Third')], max_length=2, null=True),
        ),
    ]
