# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 15:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0006_auto_20180302_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votation',
            old_name='active',
            new_name='finished',
        ),
        migrations.AddField(
            model_name='votation',
            name='days',
            field=django.contrib.postgres.fields.ranges.DateRangeField(null=True),
        ),
    ]
