# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0007_auto_20180304_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votation',
            name='days',
        ),
        migrations.AddField(
            model_name='votation',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='votation',
            name='satart_date',
            field=models.DateField(null=True),
        ),
    ]
