# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0008_auto_20180304_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='votation',
            name='satart_date',
        ),
        migrations.AddField(
            model_name='votation',
            name='end_week',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='votation',
            name='satart_vots',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='votation',
            name='satart_week',
            field=models.DateTimeField(null=True),
        ),
    ]
