# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0009_auto_20180304_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votation',
            old_name='satart_vots',
            new_name='start_vots',
        ),
        migrations.RenameField(
            model_name='votation',
            old_name='satart_week',
            new_name='start_week',
        ),
    ]
