# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 12:14
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120, null=True)),
                ('title_es', models.CharField(max_length=120, null=True)),
                ('active', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=500)),
                ('description_en', models.TextField(max_length=500, null=True)),
                ('description_es', models.TextField(max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books')),
                ('url', models.URLField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('average', models.FloatField(default=5)),
            ],
            options={
                'ordering': ['-average'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120, null=True)),
                ('title_es', models.CharField(max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120, null=True)),
                ('title_es', models.CharField(max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Nugget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('title_en', models.CharField(max_length=160, null=True)),
                ('title_es', models.CharField(max_length=160, null=True)),
                ('description', models.TextField(blank=True, max_length=350, null=True)),
                ('description_en', models.TextField(blank=True, max_length=350, null=True)),
                ('description_es', models.TextField(blank=True, max_length=350, null=True)),
                ('active', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('average', models.FloatField(default=5)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-average'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, null=True)),
                ('title_en', models.CharField(max_length=160, null=True)),
                ('title_es', models.CharField(max_length=160, null=True)),
                ('text', models.TextField(max_length=500)),
                ('text_en', models.TextField(max_length=500, null=True)),
                ('text_es', models.TextField(max_length=500, null=True)),
                ('rating', models.IntegerField()),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('all', 'All')], default='en', max_length=120)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='books', to='books.Category'),
        ),
    ]
