# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0001_initial'),
        ('books', '0003_delete_votation'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='votation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='votations.Votation'),
        ),
    ]
