# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0003_rating'),
        ('books', '0004_book_votation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': []},
        ),
        migrations.RemoveField(
            model_name='book',
            name='average',
        ),
        migrations.AddField(
            model_name='book',
            name='rate_model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='votations.Rating'),
        ),
    ]
