# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0003_rating'),
        ('books', '0005_auto_20180228_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rate_model',
        ),
        migrations.AddField(
            model_name='book',
            name='rating_model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='votations.Rating'),
        ),
    ]
